name: Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          OWNER_ID: ${{secrets.OWNER_ID}}
          TELEGRAM_API: ${{secrets.TELEGRAM_API}}
          TELEGRAM_HASH: ${{secrets.TELEGRAM_HASH}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          BOT_TOKEN: ${{secrets.BOT_TOKEN}}
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
        env:
          HD_OWNER_ID: ${{secrets.OWNER_ID}}
          HD_TELEGRAM_API: ${{secrets.TELEGRAM_API}}
          HD_TELEGRAM_HASH: ${{secrets.TELEGRAM_HASH}}
          HD_DATABASE_URL: ${{secrets.DATABASE_URL}}
          HD_BOT_TOKEN: ${{secrets.BOT_TOKEN}}
